version: "3.9"

services:
  backend:
    build: ./backend
    image: propkrl77/backend-live-explorer:1.0
   
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  
  frontend:
    build: ./frontend/cardano-live-explorer
    image: propkrl77/frontend-live-explorer:1.0
    
    ports:
     - "5173:5173"
    env_file:
      - ./frontend/cardano-live-explorer/.env

    depends_on:
      - backend
    

